title: apps.vernaillen.dev
theme: dark
color: zinc
layout:
  Monitoring:
    tab: Home
    style: row
    columns: 3
    icon: mdi-monitor-eye
  About Wouter Vernaillen:
    tab: Home
    style: row
    columns: 4
  Apps on Coolify:
    tab: Coolify VPS
    style: row
    columns: 4
    icon: si-coolify
  DevOps on Coolify:
    tab: Coolify VPS
    style: row
    columns: 3
    icon: mdi-tools
  WordPress on Combell VPS:
    tab: Combell VPS
    style: row
    columns: 4
    icon: si-combell
  Apps on Vercel.com:
    tab: Vercel
    style: row
    columns: 4
    icon: si-vercel
  Apps on Fly.io:
    tab: Fly.io
    style: row
    columns: 4
    icon: si-flyio
background:
  image: /images/vernaillen_blur.jpg
  blur: md     # none / xs / sm / md / lg / xl …
  brightness: 75
  saturate: 110
  opacity: 80